name: snipcli
version: 0.3.3
summary: Shell Snippet organiser
description: >
  Snipcli is a commandline interface for managing shell commands. Sync commands with your Snipline account or use in guest mode. Snipline lets you dynamically change command parameters easily so you never have to remember how to build a command.

confinement: classic
grade: devel

architectures:
  - amd64
  - i386

parts:
  snipcli:
    plugin: dump
    source: https://github.com/snipline/snipcli/releases/download/$SNAPCRAFT_PROJECT_VERSION/snipcli-$SNAPCRAFT_PROJECT_VERSION_linux_x86_64.tar.gz

apps:
  snipcli:
    command: snipcli
